---
name: DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  yaml-lint:
    name: Lint YAML Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4

      - name: Installation de yamllint
        run: pip install yamllint

      - name: Linting des fichiers YAML
        run: yamllint -c .yamllint.yml k8s/ .github/workflows/

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: yaml-lint
    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4

      - name: Build de l image Docker
        run: docker build -t flask-api:latest .

  trivy-fs-scan:
    name: Trivy Scan Dependances
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4

      - name: Scan Trivy filesystem
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: CRITICAL,HIGH,MEDIUM
          exit-code: 0

  trivy-image-scan:
    name: Trivy Scan Image Docker
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4

      - name: Rebuild image pour le scan
        run: docker build -t flask-api:latest .

      - name: Scan Trivy image Docker
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: flask-api:latest
          format: table
          severity: CRITICAL,HIGH,MEDIUM
          exit-code: 0

  conftest-policy:
    name: Conftest Politique Kubernetes
    runs-on: ubuntu-latest
    needs: yaml-lint
    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4

      - name: Installation de Conftest
        run: |
          CONFTEST_VERSION="0.51.0"
          wget -qO conftest.tar.gz \
            https://github.com/open-policy-agent/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz
          tar -xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Verification politique anti-root
        run: conftest test k8s/deployment.yaml --policy policy/
        continue-on-error: true
